DeliveryApp/Controllers/UserOrderController.cs
using DeliveryApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace DeliveryApp.Controllers
{
    public class UserOrderController : Controller
    {
        public async Task<IActionResult> Index()
        {
            string URI = "http://localhost:5000/api/order/";
            List<Order> entrys = new List<Order>();
            using (var client = new HttpClient())
            {
                try
                {
                    using (var response = await client.GetAsync(URI))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            var fileJsonString = await response.Content.ReadAsStringAsync();
                            entrys = JsonConvert.DeserializeObject<Order[]>(fileJsonString).ToList();
                        }
                        else
                        {
                            ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                        }

                    }
                }
                catch (HttpRequestException e)
                {
                    Console.WriteLine(e);
                }
            }
            entrys = entrys.Where(x => x.Employee1.Contains(DeliveryApp.Helpers.Common.loginResponse.Username)).ToList();
            return View(entrys);
        }

        [HttpGet("UserOrder/Edit/{OrderID}")]
        public async Task<IActionResult> Edit(string OrderID)
        {
            string URI = "http://localhost:5000/api/order/GetByID/" + OrderID;
            List<Order> entrys = new List<Order>();
            using (HttpClient client = new HttpClient())
            {
                try
                {
                    using (var response = await client.GetAsync(URI))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            var fileJsonString = await response.Content.ReadAsStringAsync();
                            entrys = JsonConvert.DeserializeObject<Order[]>(fileJsonString).ToList();
                        }
                    }
                }
                catch (HttpRequestException e)
                {
                    Console.WriteLine(e);
                }
            }
            return View(entrys[0]);
        }

        public async Task<IActionResult> Edit(Order order, String OrderID)
        {
            string URI = "http://localhost:5000/api/order/Put/" + OrderID;
            var content = new StringContent(JsonConvert.SerializeObject(order), Encoding.UTF8, "application/json");
            using (var client = new HttpClient())
            {
                using (var response = await client.PutAsync(URI, content))
                {

                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return View(order);
                    }
                }
            }
            return View();
        }

        [HttpGet("UserOrder/Edit/StartOrder/{OrderID}")]
        public async Task<IActionResult> StartOrder(string OrderID)
        {
            string URI = "http://localhost:5000/api/order/GetByID/" + OrderID;
            List<Order> entrys = new List<Order>();
            using (HttpClient client = new HttpClient())
            {
                try
                {
                    using (var response = await client.GetAsync(URI))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            var fileJsonString = await response.Content.ReadAsStringAsync();
                            entrys = JsonConvert.DeserializeObject<Order[]>(fileJsonString).ToList();
                        }
                    }
                }
                catch (HttpRequestException e)
                {
                    Console.WriteLine(e);
                }
            }
            return PartialView("StartOrder", entrys[0]);
        }

        public async Task<IActionResult> StartOrderAction(Order order, String OrderID)
        {
            string URI = "http://localhost:5000/api/order/StartOrder/" + OrderID;
            var content = new StringContent(JsonConvert.SerializeObject(order), Encoding.UTF8, "application/json");
            using (var client = new HttpClient())
            {
                using (var response = await client.PutAsync(URI, content))
                {

                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return PartialView("CancelOrder", order);
                    }
                }
            }
            return View();
        }

        [HttpGet("UserOrder/Edit/{OrderID}/GetKilometers")]
        public ActionResult GetKilometers(string OrderID, String StartPoint, String StopPoint)
        {
            String firstString = "https://rsapi.goong.io/DistanceMatrix?origins=";
            String threeString = "&destinations=";
            String fiveString = "&vehicle=";
            String sevenString = "&api_key=";
            String APiKey = "rDCEpOhGmuPf78dMFbiLh7jNEzeHaJEAj2qVM9ns";
            var uri = firstString + "20.981971,105.864323" + threeString + "21.031011,105.783206" + fiveString + "bike" + sevenString + APiKey;

            var json = "";
            using (var client = new WebClient())
            {
                json = client.DownloadString(uri);
            }

            dynamic data = JsonConvert.DeserializeObject(json);
            Decimal kilometers = data.rows[0].elements[0].distance.value;
            ViewBag.Kilometers = kilometers.ToString();

            return Json(kilometers);
        }

        public async Task<IActionResult> Ended(Order order,String OrderID)
        {
            string URI = "http://localhost:5000/api/order/Ended/" + OrderID;
            var content = new StringContent(JsonConvert.SerializeObject(order), Encoding.UTF8, "application/json");
            using (var client = new HttpClient())
            {
                using (var response = await client.PutAsync(URI, content))
                {

                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return RedirectToAction("Index");
        }

        [HttpGet("UserOrder/Edit/CancelOrder/{OrderID}")]
        public async Task<IActionResult> CancelOrder(string OrderID)
        {
            string URI = "http://localhost:5000/api/order/GetByID/" + OrderID;
            List<Order> entrys = new List<Order>();
            using (HttpClient client = new HttpClient())
            {
                try
                {
                    using (var response = await client.GetAsync(URI))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            var fileJsonString = await response.Content.ReadAsStringAsync();
                            entrys = JsonConvert.DeserializeObject<Order[]>(fileJsonString).ToList();
                        }
                    }
                }
                catch (HttpRequestException e)
                {
                    Console.WriteLine(e);
                }
            }
            return PartialView("CancelOrder", entrys[0]);
        }

        public async Task<IActionResult> CancelOrderAction(Order order, String OrderID)
        {
            string URI = "http://localhost:5000/api/order/Put/" +OrderID;
            var content = new StringContent(JsonConvert.SerializeObject(order), Encoding.UTF8, "application/json");
            using (var client = new HttpClient())
            {
                using (var response = await client.PutAsync(URI, content))
                {

                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return PartialView("CancelOrder", order);
                    }
                }
            }
            return View();
        }

        [HttpGet("UserOrder/Map/{OrderID}")]
        public async Task<ActionResult> Map(String OrderID)
        {
            string URI = "http://localhost:5000/api/order/GetByID/" + OrderID;
            List<Order> entrys = new List<Order>();
            using (HttpClient client = new HttpClient())
            {
                try
                {
                    using (var response = await client.GetAsync(URI))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            var fileJsonString = await response.Content.ReadAsStringAsync();
                            entrys = JsonConvert.DeserializeObject<Order[]>(fileJsonString).ToList();
                        }
                    }
                }
                catch (HttpRequestException e)
                {
                    Console.WriteLine(e);
                }
            }
            ViewBag.OrderID =OrderID;
            return View(entrys[0]);
        }

        [HttpGet("UserOrder/Map/{OrderID}/GetLocations")]
        public ActionResult GetLocations()
        {
            var locations = new List<Models.Locations>() {
                new Models.Locations ("105.78903","21.02524"),
                new Models.Locations("105.79553","21.03027"),

DeliveryApp/Views/UserOrder/CancelOrder.cshtml
@model DeliveryApp.Models.Order

@{
    ViewData["Title"] = "CancelOrder";
}
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

<!--Modal Body Start-->
<div class="modal-content">

    <!--Modal Header Start-->
    <div class="modal-header">
        <h4 class="modal-title">Cancel Order</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
    </div>
    <!--Modal Header End-->

    <form asp-action="CancelOrderAction">
        <div class="modal-body form-horizontal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OrderID" class="control-label"></label>
                <input asp-for="OrderID" class="form-control" />
                <span asp-validation-for="OrderID" class="text-danger"></span>
            </div>
             <div class="form-group" hidden>
                <label asp-for="ShippingType" class="control-label"></label>
                <input asp-for="ShippingType" class="form-control" />
                <span asp-validation-for="ShippingType" class="text-danger"></span>
            </div>
             <div class="form-group" hidden>
                <label asp-for="Employee1" class="control-label"></label>
                <input asp-for="Employee1" class="form-control" />
                <span asp-validation-for="Employee1" class="text-danger"></span>
            </div>
             <div class="form-group" hidden>
                <label asp-for="Employee2" class="control-label"></label>
                <input asp-for="Employee2" class="form-control" />
                <span asp-validation-for="Employee2" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="RequiredDate" class="control-label"></label>
                <input asp-for="RequiredDate" class="form-control" />
                <span asp-validation-for="RequiredDate" class="text-danger"></span>
            </div>
             <div class="form-group" hidden>
                <label asp-for="ShippedDate" class="control-label"></label>
                <input asp-for="ShippedDate" class="form-control" />
                <span asp-validation-for="ShippedDate" class="text-danger"></span>
            </div>
             <div class="form-group" hidden>
                <label asp-for="OrderFee" class="control-label"></label>
                <input asp-for="OrderFee" class="form-control" />
                <span asp-validation-for="OrderFee" class="text-danger"></span>
            </div>
             <div class="form-group" hidden>
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="StopTime" class="control-label"></label>
                <input asp-for="StopTime" class="form-control" />
                <span asp-validation-for="StopTime" class="text-danger"></span>
            </div>
             <div class="form-group" hidden>
                <label asp-for="OrderValue" class="control-label"></label>
                <input asp-for="OrderValue" class="form-control" />
                <span asp-validation-for="OrderValue" class="text-danger"></span>
            </div>
             <div class="form-group" hidden>
                <label asp-for="Mass" class="control-label"></label>
                <input asp-for="Mass" class="form-control" />
                <span asp-validation-for="Mass" class="text-danger"></span>
            </div>
             <div class="form-group" hidden>
                <label asp-for="Kilometers" class="control-label"></label>
                <input asp-for="Kilometers" class="form-control" />
                <span asp-validation-for="Kilometers" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Result" class="control-label"></label>
                <input asp-for="Result" class="form-control" value="Failure" />
                <span asp-validation-for="Result" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reason" class="control-label"></label>
                <input asp-for="Reason" class="form-control" />
                <span asp-validation-for="Reason" class="text-danger"></span>
            </div>
             <div class="form-group" hidden>
                <label asp-for="ShippingMethod" class="control-label"></label>
                <input asp-for="ShippingMethod" class="form-control" />
                <span asp-validation-for="ShippingMethod" class="text-danger"></span>
            </div>
             <div class="form-group" hidden>
                <label asp-for="BussinesStaffID" class="control-label"></label>
                <input asp-for="BussinesStaffID" class="form-control" />
                <span asp-validation-for="BussinesStaffID" class="text-danger"></span>
            </div>
             <div class="form-group" hidden>
                <label asp-for="StartPoint" class="control-label"></label>
                <input asp-for="StartPoint" class="form-control" />
                <span asp-validation-for="StartPoint" class="text-danger"></span>
            </div>
             <div class="form-group" hidden>
                <label asp-for="EndPoint" class="control-label"></label>
                <input asp-for="EndPoint" class="form-control" />
                <span asp-validation-for="EndPoint" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="WarehouseID" class="control-label"></label>
                <input asp-for="WarehouseID" class="form-control" />
                <span asp-validation-for="WarehouseID" class="text-danger"></span>
            </div>
             <div class="form-group" hidden>
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" value="Cancel"/>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
        </div>
        <!--Modal Footer Start-->
        <div class="modal-footer">
            <button data-dismiss="modal" id="cancel" class="btn btn-default" type="button">Cancel</button>
            <button class="btn btn-success relative" id="btnSubmit" type="submit">
                <i class="loader"></i>
                OK
            </button>
        </div>
        <!--Modal Footer End-->
    </form>

</div>

DeliveryApp/Views/UserOrder/Index.cshtml
@model IEnumerable<DeliveryApp.Models.Order>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />

<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
<style>
    .table-bordered {
        border: 1px solid #dddddd;
        border-collapse: separate;
        border-left: 0;
        -webkit-border-radius: 4px;
        -moz-border-radius: 4px;
        border-radius: 4px;
    }

    .table {
        width: 100%;
        margin-bottom: 20px;
        background-color: transparent;
        border-collapse: collapse;
        border-spacing: 0;
        display: table;
    }

    .widget.widget-table .table {
        margin-bottom: 0;
        border: none;
    }

    .widget.widget-table .widget-content {
        padding: 0;
    }

    .widget .widget-header + .widget-content {
        border-top: none;
        -webkit-border-top-left-radius: 0;
        -webkit-border-top-right-radius: 0;
        -moz-border-radius-topleft: 0;
        -moz-border-radius-topright: 0;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }

    .widget .widget-content {
        padding: 20px 15px 15px;
        background: #FFF;
        border: 1px solid #D5D5D5;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        border-radius: 5px;
    }

    .widget .widget-header {
        position: relative;
        height: 40px;
        line-height: 40px;
        background: #E9E9E9;
        background: -moz-linear-gradient(top, #fafafa 0%, #e9e9e9 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #fafafa), color-stop(100%, #e9e9e9));
        background: -webkit-linear-gradient(top, #fafafa 0%, #e9e9e9 100%);
        background: -o-linear-gradient(top, #fafafa 0%, #e9e9e9 100%);
        background: -ms-linear-gradient(top, #fafafa 0%, #e9e9e9 100%);
        background: linear-gradient(top, #fafafa 0%, #e9e9e9 100%);
        text-shadow: 0 1px 0 #fff;
        border-radius: 5px 5px 0 0;
        box-shadow: 0 2px 5px rgba(0,0,0,0.1),inset 0 1px 0 white,inset 0 -1px 0 rgba(255,255,255,0.7);
        border-bottom: 1px solid #bababa;
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#FAFAFA', endColorstr='#E9E9E9');
        -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr='#FAFAFA', endColorstr='#E9E9E9')";
        border: 1px solid #D5D5D5;
        -webkit-border-top-left-radius: 4px;
        -webkit-border-top-right-radius: 4px;
        -moz-border-radius-topleft: 4px;
        -moz-border-radius-topright: 4px;
        border-top-left-radius: 4px;
        border-top-right-radius: 4px;
        -webkit-background-clip: padding-box;
    }

    thead {
        display: table-header-group;
        vertical-align: middle;
        border-color: inherit;
        text-align: center;
    }

    .widget .widget-header h3 {
        top: 2px;
        position: relative;
        left: 10px;
        display: inline-block;
        margin-right: 3em;
        font-size: 14px;
        font-weight: 600;
        color: #555;
        line-height: 18px;
        text-shadow: 1px 1px 2px rgba(255, 255, 255, 0.5);
    }

    .widget .widget-header [class^="icon-"], .widget .widget-header [class*=" icon-"] {
        display: inline-block;
        margin-left: 13px;
        margin-right: -2px;
        font-size: 16px;
        color: #555;
        vertical-align: middle;
    }

    @@media (min-width: 240px) and (max-width: 1024px) {
        .table-responsive,
        .table-responsive thead,
        .table-responsive tbody,
        .table-responsive th,
        .table-responsive td,
        .table-responsive tr {
            display: block;
        }

            .table-responsive > thead > tr {
                position: absolute;
                top: -9999px;
                left: -9999px;
            }

            .table-responsive > tbody > tr {
                border-top: 1px solid #ccc;
                border-bottom: 1px solid #ccc;
            }

                .table-responsive > tbody > tr:first-child {
                    border-radius: 3px 3px 0 0;
                    border-top: none;
                }

                .table-responsive > tbody > tr:last-child {
                    border-radius: 0 0 3px 3px;
                    border-bottom: none;
                }

                .table-responsive > tbody > tr td {
                    border: none;
                    border-bottom: 1px solid #ccc;
                    position: relative;
                    padding-left: 30% !important;
                    width: 100%;
                    overflow: hidden;
                }

                    .table-responsive > tbody > tr td:before {
                        content: attr(data-title);
                        position: absolute;
                        top: 15px;
                        left: 14px;
                        width: 30%;
                        padding-right: 10px;
                        white-space: nowrap;
                        font-size: 14px;
                    }

                    .table-responsive > tbody > tr td:first-child {
                        text-align: left;
                    }

            .table-responsive.table-order > tbody > tr:nth-child(-n + 3) > td:first-child {
                padding: 25px 0 25px 30% !important;
                background-position: left 32% center;
            }

                .table-responsive.table-order > tbody > tr:nth-child(-n + 3) > td:first-child span {
                    left: 32%;
                }
    }
</style>

<h1>Index</h1>
<div class="span8">
    <div class="widget stacked widget-table action-table">

        <div class="widget-header">
            <i class="icon-th-list"></i>
            <h3>Table</h3>
        </div> <!-- /widget-header -->

        <div class="widget-content">
            <table class="table table-striped table-bordered table-customize table-responsive">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.OrderID)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ShippingType)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Employee1)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.OrderFee)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.StartTime)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.StopTime)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Result)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.WarehouseID)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Status)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Note)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.OrderID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ShippingType)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Employee1)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.OrderFee)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.StartTime)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.StopTime)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Result)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.WarehouseID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Status)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Note)
                            </td>
                            <td class="td-actions">
                                @if (item.Result != null)
                                {
                                    @if (item.Result.Equals("Success") || item.Result.Equals("Failure"))
                                    {
                                        <a class="btn btn-small btn-warning" asp-controller="UserOrder" asp-action="Edit" asp-route-id="@item.OrderID" hidden>Edit</a>
                                    }
                                    else
                                    {
                                        <a class="btn btn-small btn-warning" asp-controller="UserOrder" asp-action="Edit" asp-route-id="@item.OrderID">Edit</a>
                                    }
                                }
                                else
                                {
                                    <a class="btn btn-small btn-warning" asp-controller="UserOrder" asp-action="Edit" asp-route-id="@item.OrderID">Edit</a>
                                }
                                <a class="btn btn-small btn-success" asp-controller="UserOrder" asp-action="Details" asp-route-id="@item.OrderID">Details</a>
                                <a class="btn btn-small btn-danger" asp-controller="UserOrder" asp-action="Map" asp-route-id="@item.OrderID">Map</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div> <!-- /widget-content -->
    </div> <!-- /widget -->
</div>